server:
  port: 8080
  servlet:
    context-path: /

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    net.kaaass.kflight: DEBUG
